[icons]
# font awesome
TelegramDesktop = "ï‹†"
firefox = "ï‰©"
Alacritty = "ï„ "
Termite = "ï„ "
Thunderbird = "ïƒ "
Gpick = "ï”¿"
Slack = "ï†˜"
# smile emoji
MyNiceProgram = "ğŸ˜›"
Chromium = "ï‰¨"
zoom = "ï€½"
jetbrains-pycharm-ce = "ï„¡"
"org.qbittorrent.qBittorrent" = "ï¶"

[aliases]
TelegramDesktop = "Telegram"
firefox = "Firefox"
"Org.gnome.Nautilus" = "Nautilus"
zoom = "Zoom"
jetbrains-pycharm-ce = "pyCharm"
Alacritty = " "
Chromium = " "
Firefox = " "
Slack = " "
"org.qbittorrent.qBittorrent" = "qBittorrent"


[general]
separator = " î‚± "

[options]
remove_duplicates = true
