[icons]
# font awesome
TelegramDesktop = "ï‹†"
firefox = "ï‰©"
Alacritty = "ï„ "
Termite = "ï„ "
Thunderbird = "ïƒ "
Gpick = "ï”¿"
Slack = "ï†˜"
# smile emoji
MyNiceProgram = "ğŸ˜›"
Chromium = "ï‰¨"
zoom = "ï€½"
jetbrains-pycharm-ce = "îœ¼"
jetbrains-idea-ce = "îµ"
"org.qbittorrent.qBittorrent" = "ï¶"
"org.gnome.Nautilus" = "ï»"
eog = "ï€¾"
gnome-control-center = "ï‡"
vlc = "ï©»"

[aliases]
TelegramDesktop = "Telegram"
firefox = ""
Chromium = ""
"org.gnome.Nautilus" = "Nautilus"
zoom = "Zoom"
jetbrains-pycharm-ce = ""
jetbrains-idea-ce = ""
Alacritty = " "
"org.qbittorrent.qBittorrent" = "qBittorrent"
eog = "Image"
gnome-control-center = "Settings"
vlc = "VLC"
Vlc = "VLC"


[general]
#separator = " î‚± "
separator = " "

[options]
remove_duplicates = true
