[icons]
# font awesome
TelegramDesktop = "ï‹†"
firefox = "ï‰©"
Alacritty = "ï„ "
Termite = "ï„ "
Thunderbird = "ïƒ "
Gpick = "ï”¿"
Slack = "ï†˜"
# smile emoji
MyNiceProgram = "ğŸ˜›"
Chromium = "ï‰¨"
zoom = "ï€½"
jetbrains-pycharm-ce = "ï„¡"
jetbrains-idea-ce = "ï„¡"
"org.qbittorrent.qBittorrent" = "ï¶"
"org.gnome.Nautilus" = "ï»"
eog = "ï€¾"
gnome-control-center = "ï‡"
vlc = "ï…„"

[aliases]
TelegramDesktop = "Telegram"
firefox = ""
Chromium = ""
"org.gnome.Nautilus" = "Nautilus"
zoom = "Zoom"
jetbrains-pycharm-ce = "pyCharm"
jetbrains-idea-ce = "intelliJ"
Alacritty = " "
"org.qbittorrent.qBittorrent" = "qBittorrent"
eog = "Image"
gnome-control-center = "Settings"
vlc = "VLC"
Vlc = "VLC"


[general]
separator = " î‚± "

[options]
remove_duplicates = true
